"""initial migration

Revision ID: 4e82853d2bf2
Revises: 
Create Date: 2019-07-19 19:26:20.969288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e82853d2bf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo-list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('dateModified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo-list_title'), 'todo-list', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo-list_title'), table_name='todo-list')
    op.drop_table('todo-list')
    # ### end Alembic commands ###
