"""empty message

Revision ID: b4d0042afce9
Revises: 9663ad2d5904
Create Date: 2019-04-20 16:08:24.083595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d0042afce9'
down_revision = '9663ad2d5904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todo-list_title', table_name='todo-list')
    op.create_index(op.f('ix_todo-list_title'), 'todo-list', ['title'], unique=False)
    op.drop_constraint('todo-list_content_key', 'todo-list', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('todo-list_content_key', 'todo-list', ['content'])
    op.drop_index(op.f('ix_todo-list_title'), table_name='todo-list')
    op.create_index('ix_todo-list_title', 'todo-list', ['title'], unique=True)
    # ### end Alembic commands ###
